import{mkdir,readFile,writeFile}from"node:fs/promises";import{resolve}from"node:path";
const h=new URL(".",import.meta.url).pathname,r=resolve(h,"../.."),o=resolve(h,"05-edit/html"),F=async n=>"data:font/ttf;base64,"+(await readFile(resolve(r,"assets/fonts",n))).toString("base64"),sg=await F("SpaceGrotesk-Variable.ttf"),mo=await F("IBMPlexMono-Regular.ttf");
const S=[
{n:"01 / 06",c:"#ff4da6",cover:1,a:"Claude can help you learn -",b:"or help you avoid learning.",d:"Most students use AI to get answers faster. That saves time now, but leaves them unable to solve the next problem alone.",f:"SWIPE TO STUDY WITH AI ->"},
{n:"02 / 06",c:"#ffd83d",pill:"METHOD 01",a:"Make Claude guide you.",b:"Not solve it.",d:"Attempt the problem first. If you get stuck, request one hint at a time. Reveal the solution only after your own attempt.",p:"Guide me with one hint at a time. Wait after each hint. Do not show the full solution until I ask."},
{n:"03 / 06",c:"#37f28a",pill:"METHOD 02",a:"Turn your notes into",b:"active recall.",d:"Claude asks one question, waits for your answer, evaluates it, explains what was missing, then continues.",p:"Quiz me on these notes. Ask one question at a time. Evaluate my answer, explain what is missing, then continue."},
{n:"04 / 06",c:"#ff4da6",pill:"METHOD 03",a:"Expose your",b:"weak spots.",d:"Increase the difficulty. Track repeated mistakes. Separate careless errors from real knowledge gaps. Target those gaps next.",p:"Test me with harder questions. Track recurring mistakes and focus future questions on my weakest areas."},
{n:"05 / 06",c:"#37f28a",pill:"METHOD 04",a:"Explain it before",b:"Claude explains it.",d:"Use your own words. Claude should flag errors and missing concepts - but make you repair the explanation yourself.",p:"Check my explanation. Identify errors and missing concepts. Ask follow-ups, but do not rewrite it for me."},
{n:"06 / 06",c:"#ffd83d",pill:"METHOD 05",a:"Turn Claude into your",b:"exam simulator.",d:"Mix topics and difficulty. Use no hints. Delay feedback until the end. Then score the answers and identify what to revise.",p:"Simulate an exam on these topics. Give no hints. At the end, score me, explain mistakes, and create a revision list.",f:"USE AI TO PRACTISE THINKING BETTER."}
];
await mkdir(o,{recursive:true});
for(let i=0;i<S.length;i++){let s=S[i],v=s.cover,z=`@font-face{font-family:S;src:url(${sg})}@font-face{font-family:M;src:url(${mo})}*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1080px;overflow:hidden}body{background:#080909;color:#f5f3ef;font-family:S}.s{width:1080px;height:1080px;padding:70px 76px;position:relative;overflow:hidden}.s:before,.s:after{content:"";position:absolute;width:430px;height:430px;border-radius:50%;filter:blur(105px);opacity:.18}.s:before{background:#ffd83d;left:-190px;top:-210px}.s:after{background:${s.c};right:-170px;bottom:-220px}.t{display:flex;justify-content:space-between;font:700 12px M;letter-spacing:2px;color:#aaa;position:relative;z-index:2}.t b{color:${s.c}}.x{position:relative;z-index:2;margin-top:${v?220:145}px;${v?"text-align:center":""}}.pill{display:inline-block;background:${s.c};color:#090909;border-radius:30px;padding:10px 18px;font:700 12px M;letter-spacing:1.5px;margin-bottom:26px}h1{margin:0;font-size:${v?76:66}px;line-height:1;letter-spacing:-3px;font-weight:650}h1 span{display:block;color:${s.c}}.body{font-size:23px;line-height:1.4;color:#d2cfca;max-width:800px;margin:${v?"30px auto":"28px 0"} 0}.prompt{margin-top:54px;border:1px solid ${s.c};background:#101111;padding:26px 28px}.prompt label{display:block;color:${s.c};font:700 11px M;letter-spacing:1.8px;margin-bottom:13px}.prompt p{margin:0;color:#f2efe9;font:500 20px/1.4 S}.f{position:absolute;bottom:62px;left:0;right:0;text-align:center;color:${s.c};font:700 12px M;letter-spacing:2px}`;
let html=`<!doctype html><style>${z}</style><main class=s><div class=t><span>VECTUS - BRAIN SCIENCE</span><b>${s.n}</b></div><section class=x>${s.pill?`<div class=pill>${s.pill}</div>`:""}<h1>${s.a}<span>${s.b}</span></h1><p class=body>${s.d}</p>${s.p?`<div class=prompt><label>COPY THIS PROMPT</label><p>"${s.p}"</p></div>`:""}</section>${s.f?`<div class=f>${s.f}</div>`:""}</main>`;await writeFile(resolve(o,`slide-${String(i+1).padStart(2,"0")}.html`),html)}console.log("Generated 6 slides");