import{mkdir,readFile,writeFile}from"node:fs/promises";import{resolve}from"node:path";
const h=new URL(".",import.meta.url).pathname,r=resolve(h,"../.."),o=resolve(h,"05-edit/html"),F=async n=>"data:font/ttf;base64,"+(await readFile(resolve(r,"assets/fonts",n))).toString("base64"),sg=await F("SpaceGrotesk-Variable.ttf"),mo=await F("IBMPlexMono-Regular.ttf");
const S=[
{n:"01 / 08",c:"#ff4da6",type:"cover",a:"YOUR PRETTY NOTES",b:"ARE OVERRATED.",d:"They might help you organize.<br>That doesn't mean you're learning.",f:"SWIPE FOR THE REAL TEST ->"},
{n:"02 / 08",c:"#ffd83d",pill:"THE TRAP",a:"You spent 2 hours",b:"making perfect notes.",d:"Everything is highlighted.<br>Everything looks organized.<br><br>And it feels productive.",call:"THAT'S THE PROBLEM."},
{n:"03 / 08",c:"#37f28a",pill:"RECOGNITION",a:"Familiar",b:"doesn't mean learned.",d:"When you reread your notes, the information looks familiar. Your brain says: <strong>\"Yeah, I know this.\"</strong>",call:"CLOSE THE NOTES. CAN YOU EXPLAIN IT?"},
{n:"04 / 08",c:"#ff4da6",pill:"THE TEST",a:"Try this",b:"right now.",d:"Pick something you studied yesterday.<br><br>Close your notes.<br>Now explain it without looking.",call:"STUCK? THAT'S RECOGNIZING VS. KNOWING."},
{n:"05 / 08",c:"#37f28a",pill:"DO THIS INSTEAD",a:"Make your brain",b:"work.",list:["Close the book","Ask yourself questions","Explain concepts from memory","Solve problems without help","Check what you got wrong"]},
{n:"06 / 08",c:"#ffd83d",pill:"IMPORTANT",a:"Notes aren't",b:"useless.",d:"They're great for organizing information, understanding new concepts, and creating a reference.",call:"BUT CREATING NOTES SHOULDN'T BE THE END."},
{n:"07 / 08",c:"#ff4da6",type:"quote",a:"Don't study until",b:"you've seen everything.",a2:"Study until you can",b2:"recall it without seeing it.",f:"SAVE THIS FOR YOUR NEXT STUDY SESSION."},
{n:"08 / 08",c:"#37f28a",type:"cta",pill:"BE HONEST",a:"How much of your",b:"\"study time\"",d:"is actually just making notes?",f:"DROP YOUR ANSWER BELOW!“"}
];
await mkdir(o,{recursive:true});
for(let i=0;i<S.length;i++){let s=S[i],center=["cover","quote","cta"].includes(s.type),z=`@font-face{font-family:S;src:url(${sg})}@font-face{font-family:M;src:url(${mo})}*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1080px;overflow:hidden}body{background:#080909;color:#f5f3ef;font-family:S}.s{width:1080px;height:1080px;padding:70px 76px;position:relative;overflow:hidden}.s:before,.s:after{content:"";position:absolute;width:430px;height:430px;border-radius:50%;filter:blur(105px);opacity:.18}.s:before{background:#ffd83d;left:-190px;top:-210px}.s:after{background:${s.c};right:-170px;bottom:-220px}.top{display:flex;justify-content:space-between;font:700 12px M;letter-spacing:2px;color:#aaa;position:relative;z-index:2}.top b{color:${s.c}}.x{position:relative;z-index:2;margin-top:${center?190:140}px;${center?"text-align:center":""}}.pill{display:inline-block;background:${s.c};color:#090909;border-radius:30px;padding:10px 18px;font:700 12px M;letter-spacing:1.6px;margin-bottom:26px}h1{margin:0;font-size:${s.type=="cover"?83:s.type=="quote"?66:70}px;line-height:1;letter-spacing:-3px;font-weight:660}h1 span{display:block;color:${s.c}}.second{margin-top:70px}.body{font-size:25px;line-height:1.42;color:#d2cfca;max-width:800px;margin:${center?"32px auto":"30px 0"} 0}.body strong{color:${s.c}}.call{margin-top:62px;border-top:2px solid ${s.c};padding-top:20px;color:${s.c};font:700 15px M;letter-spacing:1.6px}.list{margin-top:45px;display:grid;gap:15px}.item{border:1px solid #30312f;background:#101111;padding:17px 22px;font-size:21px}.item b{color:${s.c};margin-right:14px}.foot{position:absolute;bottom:62px;left:0;right:0;text-align:center;color:${s.c};font:700 12px M;letter-spacing:2px}`;
const items=s.list?`<div class=list>${s.list.map(x=>`<div class=item><b?’</b>${x}</div>`).join("")}</div>`:"",second=s.a2?`<h1 class=second>${s.a2}<span>${s.b2}</span></h1>`:"";
await writeFile(resolve(o,`slide-${String(i+1).padStart(2,"0")}.html`),`<!doctype html><style>${z}</style><main class=s><div class=top><span>VECTUS - BRAIN SCIENCE</span><b>${s.n}</b></div><section class=x>${s.pill?`<div class=pill>${s.pill}</div>`:""}<h1>${s.a}<span>${s.b}</span></h1>${second}${s.d?`<p class=body>${s.d}</p>`:""}${items}${s.call?`<div class=call>${s.call}</div>`:""}</section>${s.f?`<div class=foot>${s.f}</div>`:""}</main>`)}console.log("Generated 8 slides");